version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=game_bot_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_secure_password_here
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 game_bot_admin.wsgi:application
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DB_NAME=game_bot_db
      - DB_USER=postgres
      - DB_PASSWORD=your_secure_password_here
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db

  bot:
    build: .
    command: python freefire.py
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - DB_NAME=game_bot_db
      - DB_USER=postgres
      - DB_PASSWORD=your_secure_password_here
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=your-secret-key-here
    depends_on:
      - db
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
