# Generated by Django 5.2.4 on 2025-09-07 01:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('birthdate', models.CharField(max_length=10, verbose_name="Tug'ilgan sana")),
                ('freefire_id', models.CharField(max_length=50, verbose_name='Free Fire ID')),
                ('direction', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram User ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Bot foydalanuvchisi',
                'verbose_name_plural': 'Bot foydalanuvchilari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kanal nomi')),
                ('channel_type', models.CharField(choices=[('telegram', 'Telegram'), ('youtube', 'YouTube'), ('instagram', 'Instagram')], max_length=20, verbose_name='Kanal turi')),
                ('url', models.URLField(verbose_name='Havola')),
                ('is_required', models.BooleanField(default=True, verbose_name='Majburiy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Obuna kanali',
                'verbose_name_plural': 'Obuna kanallari',
            },
        ),
    ]
