# Generated by Django 5.2.4 on 2025-09-07 02:00

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name="To'liq ism")),
                ('birthdate', models.CharField(max_length=10, verbose_name="Tug'ilgan sana")),
                ('freefire_id', models.CharField(max_length=50, verbose_name='Free Fire ID')),
                ('direction', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='Telegram User ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Username')),
                ('registration_type', models.CharField(choices=[('solo', 'Solo'), ('team', 'Jamoa')], max_length=10, verbose_name="Ro'yxatdan o'tish turi")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "O'yinchi",
                'verbose_name_plural': "O'yinchilar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoloPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for_team', models.BooleanField(default=True, verbose_name='Jamoa qidirayapti')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solo_profile', to='bot_data.player', verbose_name="O'yinchi")),
            ],
            options={
                'verbose_name': "Solo o'yinchi",
                'verbose_name_plural': "Solo o'yinchilar",
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jamoa nomi')),
                ('referral_code', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Referal kodi')),
                ('max_members', models.IntegerField(default=4, verbose_name="Maksimal a'zolar soni")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan vaqt')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('captain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to='bot_data.player', verbose_name='Jamoa sardori')),
            ],
            options={
                'verbose_name': 'Jamoa',
                'verbose_name_plural': 'Jamoalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BotUser',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='bot_data.team', verbose_name='Jamoa'),
        ),
    ]
