# Generated by Django 5.2.4 on 2025-09-07 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_data', '0002_player_soloplayer_team_delete_botuser_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('solo', 'Solo'), ('team_player', "Jamoa o'yinchisi")], default='solo', max_length=15, verbose_name='Status'),
        ),
    ]
