# Generated by Django 5.2.4 on 2025-09-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_data', '0003_player_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='direction',
            field=models.CharField(default='Toshkent', max_length=100, verbose_name='Viloyat'),
        ),
    ]
